name: hotuiti
channels:
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.10.13
  
  # Core scientific packages
  - numpy=1.24.4
  - scipy=1.11.4
  - matplotlib=3.8.2
  
  # 3D mesh processing
  - trimesh=4.0.10
  - rtree=1.1.0
  - shapely=2.0.2
  - networkx=3.2.1
  - pillow=10.2.0
  
  # Interactive visualization
  - plotly=5.18.0
  
  # Development tools
  - pip>=23.0
  - setuptools>=65.5.0
  
  # Additional pip packages not in conda
  - pip:
    # Add any pip-only packages here if needed